# Generated by Django 5.0.1 on 2024-05-29 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='mechanic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicle.mechanic'),
        ),
        migrations.AlterField(
            model_name='vehicle_type',
            name='vehicletype',
            field=models.CharField(max_length=50),
        ),
    ]
